// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/gogf/gf-demo-user/v2/internal/logic/bizctx"
	_ "github.com/gogf/gf-demo-user/v2/internal/logic/middleware"
	_ "github.com/gogf/gf-demo-user/v2/internal/logic/session"
	_ "github.com/gogf/gf-demo-user/v2/internal/logic/user"
)
