// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// User is the golang structure for table user.
type User struct {
	Id   uint   `orm:"id,primary" json:"id"`   //
	Name string `orm:"name"       json:"name"` //
}
