// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-17 21:30:31
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `json:"id"       description:"用户ID"`
	Passport string      `json:"passport" description:"用户账号"`
	Password string      `json:"password" description:"用户密码"`
	Nickname string      `json:"nickname" description:"用户昵称"`
	CreateAt *gtime.Time `json:"createAt" description:"创建时间"`
	UpdateAt *gtime.Time `json:"updateAt" description:"更新时间"`
}
